version: '3.8'

services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - ./backend/tmp/db:/var/lib/mysql

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/vendor
      - /app/tmp
      - /app/log
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
