version: '3.8'

volumes:
  mysql_volume:

services:
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '13306:3306'
    volumes:
      - ./backend/tmp/db:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
      - /app/vendor
      - /app/tmp
      - /app/log
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_PORT: 3306
      DB_HOST: db
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
     - backend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
